/**
 * Execução Manual do AutoGeneratorDDD
 * Este arquivo mostra exatamente como executar o gerador passo a passo
 */

console.log('🔍 DEBUG: Iniciando arquivo manual-execution.ts');

let autoGenerateDDDFromZodSchemas, AutoGeneratorDDD;

try {
  console.log('📦 DEBUG: Tentando importar auto-generator-ddd...');
  const module = await import('../src/auto-generator-ddd.js');
  autoGenerateDDDFromZodSchemas = module.autoGenerateDDDFromZodSchemas;
  AutoGeneratorDDD = module.AutoGeneratorDDD;
  console.log('✅ DEBUG: Importação bem-sucedida!');
} catch (importError) {
  console.error('❌ DEBUG: Erro na importação:', importError);
  console.error('❌ DEBUG: Stack trace:', importError.stack);
  process.exit(1);
}

// =========================================
// MÉTODO 1: Usando a função utilitária
// =========================================

export async function executarGeradorSimples() {
  console.log('🚀 Executando via função utilitária...\n');

  await autoGenerateDDDFromZodSchemas({
    modulesPath: 'examples',           // ← Procura schemas aqui
    domainPath: 'src/domain',          // ← Gera domínio aqui
    boundedContext: 'user',            // ← Nome do contexto
    verbose: true,                     // ← Log detalhado
    force: true,                       // ← Sobrescrever arquivos
    dryRun: true                       // ← Apenas simular (mude para false)
  });

  console.log('✅ Função utilitária executada!');
}

// =========================================
// MÉTODO 2: Usando a classe diretamente
// =========================================

export async function executarGeradorClasse() {
  console.log('🚀 Executando via classe...\n');

  const generator = new AutoGeneratorDDD({
    modulesPath: 'examples',
    domainPath: 'src/domain',
    boundedContext: 'user',
    verbose: true,
    force: true,
    dryRun: true
  });

  await generator.generate();

  console.log('✅ Classe executada!');
}

// =========================================
// MÉTODO 3: Execução passo a passo
// =========================================

export async function executarPassoAPasso() {
  console.log('🚀 Executando passo a passo...\n');

  console.log('📂 Etapa 1: Criando instância do gerador...');
  const generator = new AutoGeneratorDDD({
    modulesPath: 'examples',
    domainPath: 'src/domain',
    boundedContext: 'user',
    verbose: true,
    force: true,
    dryRun: true
  });

  console.log('🔍 Etapa 2: Procurando schemas Zod...');
  // O generate() faz automaticamente

  console.log('🏗️  Etapa 3: Gerando estrutura DDD...');
  await generator.generate();

  console.log('📊 Etapa 4: Verificando módulos gerados...');
  const modulos = AutoGeneratorDDD.listGeneratedDDDModules('examples');
  console.log(`📦 Módulos encontrados: ${modulos.join(', ')}`);

  console.log('✅ Execução passo a passo concluída!');
}

// =========================================
// FUNÇÃO PRINCIPAL PARA EXECUÇÃO MANUAL
// =========================================

export async function executarManual() {
  console.log('🎯 EXECUÇÃO MANUAL DO AUTOGENERATORDDD');
  console.log('======================================\n');

  try {
    console.log('🔧 DEBUG: Tentando executar executarGeradorClasse()...');

    await executarGeradorClasse();       // Método 2 - Classe

    console.log('\n🎉 Execução manual concluída com sucesso!');
    console.log('\n📋 PRÓXIMOS PASSOS:');
    console.log('1. Verifique os arquivos em examples/user/');
    console.log('2. Verifique os arquivos em src/domain/user-example/');
    console.log('3. Mude dryRun: false para gerar arquivos reais');
    console.log('4. Execute: npx tsx examples/manual-execution.ts');

  } catch (error) {
    console.error('\n❌ Erro na execução manual:', error);
    console.error('\n🔧 POSSÍVEIS SOLUÇÕES:');
    console.log('1. Verifique se examples/user.schema.ts existe');
    console.log('2. Verifique se src/auto-generator-ddd.ts compila');
    console.log('3. Execute: npx tsc --noEmit src/auto-generator-ddd.ts');
    console.error('\n📋 Stack trace completo:', error.stack);
  }
}

// =========================================
// EXECUÇÃO AUTOMÁTICA
// =========================================

// Executar automaticamente quando o arquivo for chamado diretamente
if (import.meta.url === `file://${process.argv[1]}`) {
  executarManual().catch(console.error);
}
