#!/usr/bin/env bun
/**
 * Script simples para executar o AutoGeneratorDDD
 * Uso: bun run examples/run-ddd-generator.ts
 */

import { autoGenerateDDDFromZodSchemas } from '../src/auto-generator-ddd.js';

async function main() {
  console.log('🎯 Executando AutoGeneratorDDD');
  console.log('================================\n');

  console.log('📋 Configurações:');
  console.log('  • Modules Path: src/modules');
  console.log('  • Domain Path: src/domain');
  console.log('  • Bounded Context: user-example');
  console.log('  • Verbose: true');
  console.log('  • Force: false');
  console.log('  • Dry Run: true (mude para false para gerar arquivos reais)\n');

  try {
    await autoGenerateDDDFromZodSchemas({
      modulesPath: 'examples',
      domainPath: 'src/domain',
      boundedContext: 'user-example',
      verbose: true,
      force: true,
      dryRun: true // ⚠️ MUDE PARA false PARA GERAR ARQUIVOS REAIS
    });

    console.log('\n✅ Geração DDD concluída com sucesso!');
    console.log('\n📁 Verifique os arquivos gerados em:');
    console.log('  • src/modules/user-example/');
    console.log('  • src/domain/user-example/');

    console.log('\n💡 Para gerar arquivos reais, mude dryRun: true para false');

  } catch (error) {
    console.error('\n❌ Erro na geração DDD:', error);
    process.exit(1);
  }
}

// Executar apenas se chamado diretamente
if (import.meta.main) {
  main().catch(console.error);
}
