@echo off
REM Script Batch para executar AutoGeneratorDDD no Windows
REM Uso: double-click neste arquivo ou execute no cmd

echo 🎯 Executando AutoGeneratorDDD via Batch Script
echo ==================================================
echo.

echo 📋 Configurações:
echo   • Modules Path: examples
echo   • Domain Path: src/domain
echo   • Bounded Context: user-example
echo   • Verbose: true
echo   • Force: true
echo   • Dry Run: true (mude para false para gerar arquivos reais)
echo.

echo 🚀 Iniciando geração DDD...
echo.

REM Criar arquivo temporário com o script
echo import { autoGenerateDDDFromZodSchemas } from './src/auto-generator-ddd.js'; > temp_generator.mjs
echo. >> temp_generator.mjs
echo console.log('🎯 AutoGeneratorDDD iniciado via Batch...'); >> temp_generator.mjs
echo. >> temp_generator.mjs
echo await autoGenerateDDDFromZodSchemas({ >> temp_generator.mjs
echo   modulesPath: 'examples', >> temp_generator.mjs
echo   domainPath: 'src/domain', >> temp_generator.mjs
echo   boundedContext: 'user-example', >> temp_generator.mjs
echo   verbose: true, >> temp_generator.mjs
echo   force: true, >> temp_generator.mjs
echo   dryRun: true >> temp_generator.mjs
echo }); >> temp_generator.mjs
echo. >> temp_generator.mjs
echo console.log('✅ Geração concluída!'); >> temp_generator.mjs

REM Executar com Node.js
node temp_generator.mjs

REM Verificar se executou com sucesso
if %errorlevel% equ 0 (
    echo.
    echo ✅ Script executado com sucesso!
    echo.
    echo 📁 Verifique os arquivos gerados em:
    echo   • examples\user-example\
    echo   • src\domain\user-example\
    echo.
    echo 💡 Para gerar arquivos reais, edite dryRun: false neste arquivo
) else (
    echo.
    echo ❌ Erro na execução do script!
    echo.
    echo 🔧 Possíveis soluções:
    echo   1. Verifique se Node.js está instalado
    echo   2. Execute como Administrador
    echo   3. Verifique se examples\user.schema.ts existe
    echo   4. Execute: npx tsc --noEmit src\auto-generator-ddd.ts
)

REM Limpar arquivo temporário
del temp_generator.mjs

echo.
echo 🏁 Script concluído. Pressione qualquer tecla para fechar...
pause > nul
