/**
 * Exemplo de uso do AutoGeneratorDDD
 * Demonstra como gerar arquitetura DDD completa baseada em schemas Zod
 */

import { autoGenerateDDDFromZodSchemas, AutoGeneratorDDD } from '../src/auto-generator-ddd.js';

/**
 * Exemplo 1: Usando a função utilitária simples
 */
async function exemploSimples() {
  console.log('🚀 Exemplo 1: Geração DDD simples');

  try {
    await autoGenerateDDDFromZodSchemas({
      modulesPath: 'src/modules',
      domainPath: 'src/domain',
      boundedContext: 'user-management',
      verbose: true,
      force: false,
      dryRun: false // Mude para false para gerar arquivos reais
    });

    console.log('✅ Geração DDD concluída!');
  } catch (error) {
    console.error('❌ Erro na geração DDD:', error);
  }
}

/**
 * Exemplo 2: Usando a classe diretamente com mais controle
 */
async function exemploAvancado() {
  console.log('🚀 Exemplo 2: Geração DDD avançada com classe');

  const generator = new AutoGeneratorDDD({
    modulesPath: 'src/modules',
    domainPath: 'src/domain',
    boundedContext: 'user-management',
    verbose: true,
    force: false,
    dryRun: false // Mude para false para gerar arquivos reais
  });

  try {
    await generator.generate();
    console.log('✅ Geração DDD avançada concluída!');

    // Listar módulos gerados
    const modulosGerados = AutoGeneratorDDD.listGeneratedDDDModules('src/modules');
    console.log(`📦 Módulos DDD gerados: ${modulosGerados.join(', ')}`);

  } catch (error) {
    console.error('❌ Erro na geração DDD avançada:', error);
  }
}

/**
 * Exemplo 3: Limpeza de módulos gerados (para desenvolvimento)
 */
async function exemploLimpeza() {
  console.log('🧹 Exemplo 3: Limpando módulos DDD gerados');

  // Listar antes da limpeza
  const antes = AutoGeneratorDDD.listGeneratedDDDModules('src/modules');
  console.log(`📦 Módulos antes da limpeza: ${antes.join(', ')}`);

  // Limpar (dry run por segurança)
  AutoGeneratorDDD.cleanGeneratedDDDModules('src/modules', true);

  // Listar depois da limpeza
  const depois = AutoGeneratorDDD.listGeneratedDDDModules('src/modules');
  console.log(`📦 Módulos depois da limpeza: ${depois.join(', ')}`);
}

/**
 * Exemplo 4: Geração com múltiplos bounded contexts
 */
async function exemploMultiplosContextos() {
  console.log('🚀 Exemplo 4: Geração com múltiplos bounded contexts');

  const contextos = [
    { name: 'user-management', path: 'src/modules/users' },
    { name: 'product-catalog', path: 'src/modules/products' },
    { name: 'order-processing', path: 'src/modules/orders' }
  ];

  for (const contexto of contextos) {
    console.log(`🏗️  Gerando bounded context: ${contexto.name}`);

    const generator = new AutoGeneratorDDD({
      modulesPath: contexto.path,
      domainPath: `src/domain/${contexto.name}`,
      boundedContext: contexto.name,
      verbose: false, // Menos verbose para múltiplos
      force: false,
      dryRun: false
    });

    try {
      await generator.generate();
      console.log(`✅ ${contexto.name} gerado com sucesso!`);
    } catch (error) {
      console.error(`❌ Erro ao gerar ${contexto.name}:`, error);
    }
  }
}

/**
 * Exemplo 5: Configuração personalizada por ambiente
 */
async function exemploConfiguracaoAmbiente() {
  console.log('🚀 Exemplo 5: Configuração personalizada por ambiente');

  // Configurações diferentes por ambiente
  const configs = {
    development: {
      verbose: true,
      dryRun: false,
      force: true
    },
    production: {
      verbose: false,
      dryRun: false,
      force: false
    }
  };

  const ambiente = process.env.NODE_ENV || 'development';
  const config = configs[ambiente as keyof typeof configs];

  console.log(`🌍 Ambiente: ${ambiente}`);
  console.log(`⚙️  Configuração:`, config);

  const generator = new AutoGeneratorDDD({
    modulesPath: 'src/modules',
    domainPath: 'src/domain',
    boundedContext: 'app',
    ...config
  });

  try {
    await generator.generate();
    console.log(`✅ Geração DDD para ${ambiente} concluída!`);
  } catch (error) {
    console.error(`❌ Erro na geração para ${ambiente}:`, error);
  }
}

/**
 * Função principal - execute os exemplos desejados
 */
async function main() {
  console.log('🎯 Teste do AutoGeneratorDDD');
  console.log('================================\n');

  // Execute os exemplos (descomente os que quiser testar)

  // Exemplo básico
  await exemploSimples();
  console.log('\n');

  // Exemplo avançado
  await exemploAvancado();
  console.log('\n');

  // Exemplo de limpeza
  await exemploLimpeza();
  console.log('\n');

  // Exemplo múltiplos contextos
  // await exemploMultiplosContextos();
  // console.log('\n');

  // Exemplo configuração ambiente
  // await exemploConfiguracaoAmbiente();
  // console.log('\n');

  console.log('🎉 Todos os exemplos executados!');
}

// Executar se chamado diretamente
// if (require.main === module) {
//   main().catch(console.error);
// }

export {
  exemploSimples,
  exemploAvancado,
  exemploLimpeza,
  exemploMultiplosContextos,
  exemploConfiguracaoAmbiente
};
