// Teste simples de importação
console.log('🔍 Testando importação simples...');

try {
  console.log('📦 Importando...');
  const module = await import('../src/auto-generator-ddd.js');
  console.log('✅ Importação OK!');
  console.log('📦 Módulos disponíveis:', Object.keys(module));
  console.log('🎯 AutoGeneratorDDD existe:', typeof module.AutoGeneratorDDD);
  console.log('🎯 autoGenerateDDDFromZodSchemas existe:', typeof module.autoGenerateDDDFromZodSchemas);
} catch (error) {
  console.error('❌ Erro:', error.message);
  console.error('📋 Stack:', error.stack);
}
