/**
 * Integração do Gerador DDD a partir de Interfaces TypeScript
 * com o sistema principal @purecore/apify
 */

import { generateDDDFromInterface } from './generators/ddd-from-interfaces';
import { autoGenerateDDDFromZodSchemas } from './auto-generator-ddd';

// Interface para definir opções de geração combinada
export interface CombinedGenerationOptions {
  useZodSchemas?: boolean;
  useInterfaceSchemas?: boolean;
  modulesPath?: string;
  domainPath?: string;
  force?: boolean;
  verbose?: boolean;
  dryRun?: boolean;
  boundedContext?: string;
}

/**
 * Função para gerar módulos DDD combinando diferentes abordagens:
 * - Zod schemas (existente)
 * - Interfaces TypeScript (nova funcionalidade)
 */
export async function generateCombinedDDD(
  interfaces?: Record<string, string>, // nome => código da interface
  options: CombinedGenerationOptions = {}
): Promise<void> {
  console.log('🚀 Iniciando geração DDD combinada...');
  
  const {
    useZodSchemas = true,
    useInterfaceSchemas = true,
    modulesPath = 'src/modules',
    ...restOptions
  } = options;

  // Gerar a partir de interfaces TypeScript se solicitado
  if (useInterfaceSchemas && interfaces) {
    console.log('📝 Gerando a partir de interfaces TypeScript...');
    
    for (const [name, interfaceCode] of Object.entries(interfaces)) {
      console.log(`   Gerando módulo para: ${name}`);
      
      try {
        await generateDDDFromInterface(interfaceCode, {
          modulesPath,
          ...restOptions
        });
        
        console.log(`   ✅ Módulo ${name} gerado com sucesso`);
      } catch (error) {
        console.error(`   ❌ Erro ao gerar módulo ${name}:`, error);
      }
    }
  }

  // Gerar a partir de Zod schemas se solicitado
  if (useZodSchemas) {
    console.log('🔍 Gerando a partir de schemas Zod existentes...');
    
    try {
      await autoGenerateDDDFromZodSchemas({
        modulesPath,
        ...restOptions
      });
      
      console.log('✅ Geração a partir de Zod schemas concluída');
    } catch (error) {
      console.error('❌ Erro na geração a partir de Zod schemas:', error);
    }
  }

  console.log('🎉 Geração DDD combinada concluída!');
}

/**
 * Exemplo de uso combinado
 */
export async function runCombinedExample(): Promise<void> {
  // Definir interfaces TypeScript para geração
  const interfaces: Record<string, string> = {
    User: `
interface User {
  id: string;
  name: string;
  email: string;
  age: number;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}`,
    Product: `
interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}`
  };

  // Executar geração combinada
  await generateCombinedDDD(interfaces, {
    modulesPath: 'src/modules',
    verbose: true,
    force: true
  });
}

// Exportar para uso direto
export {
  generateDDDFromInterface,
  DDDFromInterfacesGenerator
} from './generators/ddd-from-interfaces';

// Exportar tipos úteis
export type {
  DDDGenerationOptions
} from './generators/ddd-from-interfaces';

console.log('✅ Módulo de integração DDD carregado com sucesso');